force-app/main/default/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Age__c</fullName>
        <formula>Date_of_Birth__c - Today()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Age</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Married__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Married</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sex__c</fullName>
        <label>Sex</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/selectorClasses/StudentSelector.cls
public with sharing class StudentSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                Student__c.Id,
                Student__c.Age__c, 
                Student__c.Class__c,
                Student__c.Date_of_Birth__c,
                Student__c.Email__c,
                Student__c.First_Name__c,
                Student__c.Last_Name__c,
                Student__c.Sex__c,
                Student__c.Married__c,
                Student__c.Name
        };
    }
     public Schema.SObjectType getSObjectType() {
        return Student__c.sObjectType;
    }
    public List<Student__c> selectById(Set<ID> idSet) {
        return (List<Student__c>) selectSObjectsById(idSet);
    }

    public List<Student__c> selectStudentsByClassIds(List<Id> classIds){
        return [SELECT Id FROM Student__c WHERE Class__c in :classIds];
        
        // return (List<Student__c>) Database.query(
        //     newQueryFactory()
        //     .setCondition(' Class__c in :'+ classIds)
        //     .toSOQL()
        // );
    }

    public Map<Id,Integer> getStudentCountOfClasses(List<Id> classes){

        List<AggregateResult> result = [SELECT COUNT(Id) studentCount, Class__c FROM Student__c GROUP BY Class__c Having Class__c in : classes ]; 

        // List<AggregateResult> result = Database.query(
        //     newQueryFactory()
        //     .selectField('Count(Id) studentCount')
        //     .selectField('Class__c')
        //     .toSOQL() + 'GROUP BY Class__c HAVING Class__c in :'+classes); 
        Map<Id,Integer> classIdToStudentCountMap = new Map<Id,Integer>();
        for(AggregateResult r: result){
            classIdToStudentCountMap.put((Id)r.get('Class__c'),(Integer)r.get('studentCount'));
        }
        return classIdToStudentCountMap; 
    } 

    public Set<Id> select_returnsClassIds_whereThereAreMoreThanTwoFemaleStudent_fromClassIds(List<Class__c> classes){
        List<AggregateResult> result = Database.query(
            newQueryFactory()
            .selectField('Class__c')
            .selectField('Count(Id) femaleStudentCount')
            .setCondition('Sex__c = \'Female\'')
            .toSOQL() + 'group by class__c having count(Id)>1 and class__c in :'+classes); 
        Set<Id> classIds = new Set<Id>();
        for(AggregateResult r:result){
            classIds.add((Id)r.get('class__c'));
        }
        return classIds; 
    }

}