force-app/main/default/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/domainClasses/Classes.cls
public class Classes extends fflib_SObjectDomain {
     public Classes(List<Class__c> sObjectList) {
        super(sObjectList);
    }
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<Class__c> sObjectList) {
            return new Classes(sObjectList);
        }
    }

    public override void onAfterUpdate(Map<Id,SObject> existingRecords){
        List<Class__c> classes = (List<Class__c>)Records; 
        List<Id> classIds = new List<Id>();
        for(Class__c cls: classes){
            if(cls.Custom_Status__c == 'Reset'){
                classIds.add(cls.Id);
            }
        }
        List<Student__c> studentsToDelete = new StudentSelector().selectStudentsByClassIds(classIds);
        StudentService.deleteStudents(studentsToDelete); 
        
    }

    public override void onBeforeDelete(){
       List<Class__c> classes = (List<Class__c>)Records; 
       
       Set<Id> filterIds = new StudentSelector().select_returnsClassIds_whereThereAreMoreThanTwoFemaleStudent_fromClassIds(classes); 
       
       for(Class__c cls: classes){
            if(filterIds.contains(cls.Id)){
                cls.addError('Class cannot be deleted');
            }    
        } 
    }
}