force-app/main/default/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Max_Size__c</fullName>
        <label>Max Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>No_of_Students__c</fullName>
        <label>No of Students</label>
        <summaryForeignKey>Student__c.Class__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/selectorClasses/ClassSelector.cls
public with sharing class ClassSelector extends fflib_SObjectSelector {
     public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                 Class__c.Id,
                 Class__c.Name,
                 Class__c.Name__c,
                 Class__c.Max_Size__c,
                 Class__c.No_of_Students__c,
                 Class__c.Custom_Status__c
        }; 
    }
     public Schema.SObjectType getSObjectType() {
        return Class__c.sObjectType;
    }
    public List<Class__c> selectById(Set<ID> idSet) {
        return (List<Class__c>) selectSObjectsById(idSet);
    }
}