force-app/main/default/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>Max_Size__c</fullName>
        <label>Max Size</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/serviceClasses/StudentService.cls
public with sharing class StudentService {

    public static void deleteStudents(List<Student__c> students){
        fflib_SObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new Schema.SObjectType[]{
                Student__c.SObjectType
            }
        );
        for(Student__c stud: students){
            uow.registerDeleted(stud); 
        } 
        uow.commitWork();
    }

    public static Set<Id> getUnavaliableClassIdstoRevokeInsertStudent(List<Id> classId){
        Map<Id,Integer> classToStudentCountMap = new StudentSelector().getStudentCountOfClasses(classId);
        List<Class__c> classDetails = new ClassSelector().selectById(new Set<Id>(classId));
        Set<Id> filteredClassIds = new Set<Id>();
        for(Class__c cls: classDetails){
            if(classToStudentCountMap.get(cls.Id)>=cls.Max_Size__c){
                filteredClassIds.add(cls.Id);
            }
        }
        return filteredClassIds;
    }
}