force-app/main/default/objects/Class__c.object
<CustomObject>
    <label>Class</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ClassStudent.cls
public with sharing class ClassStudent {
    public static List<String> getStudents(String classId){
		List<Student__c> students = [SELECT First_Name__c,Last_Name__c from student__c where class__r.name =:classId];
        List<String> names = new List<String>(); 
        for(Student__c student: students){
            String name = student.First_Name__c+' '+student.Last_Name__c;
            System.debug(student.First_Name__c+' '+student.Last_Name__c);
        }
        return names; 
	}

    public static Map<String,Set<Id>> getStudentsId(){
        List<Student__c> students = [SELECT Id FROM student__c]; 
        Map<String,Set<Id>> mapStudent = new Map<String,Set<Id>>(); 
        for(Student__c student: students){
            Set<Id> classId = mapStudent.get(student.class__r.Id); 
            if(classId != null){
                classId.add(student.Id); 
            }else{
                classId = new Set<Id>(); 
                classId.add(student.Id);
            }
        }
        return mapStudent;  
    }
}