force-app/main/default/objects/Class__c.object
<CustomObject>
    <fields>
        <fullName>MyCount__c</fullName>
        <label>MyCount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Class</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Class ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c.object
<CustomObject>
    <fields>
        <fullName>Class__c</fullName>
        <label>Class</label>
        <referenceTo>Class__c</referenceTo>
        <relationshipLabel>Students</relationshipLabel>
        <relationshipName>Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Student</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/domainClasses/Students.cls
public class Students extends fflib_SObjectDomain {
    public Students(List<Student__c> sObjectList) {
        super(sObjectList);
    }
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<Student__c> sObjectList) {
            return new Students(sObjectList);
        }
    }

    public override void onBeforeInsert(){
        List<Student__c> students = (List<Student__c>) Records; 
        
        // Check if classes have avaliable seats
        List<Id> classIds = new List<Id>();
        for(Student__c student:students){
                classIds.add(student.Class__c);
        }

        Set<Id> filteredClassIds = StudentService.getUnavaliableClassIdstoRevokeInsertStudent(classIds);
        
        for(Student__c student: students){
            if(filteredClassIds.contains(student.Class__c)){
                student.addError('No Seats Available');
            }
        }
    }

    public override void onAfterInsert(){
        List<Student__c> students = (List<Student__c>) Records;
        incrementClassMyCount(students); 
    }
    public override void onAfterDelete(){
        List<Student__c> students = (List<Student__c>) Records;
        decrementClassMyCount(students); 
    }

    public override void onAfterUpdate(Map<Id,SObject> existingRecords){
        List<Student__c> students = (List<Student__c>) Records;
        decrementClassMyCount((List<Student__c>)existingRecords.values()); 
        incrementClassMyCount(students); 
    }

    public void decrementClassMyCount(List<Student__c> students){
        Set<Id> classIDs = new Set<Id>(); 
        for(Student__c student: students){
            classIDs.add(student.Class__c);
        }
        List<Class__c> classList = new ClassSelector().selectById(classIds); 
        Map<Id,Class__c> classMap = new Map<Id,Class__c>(); 
        for(Class__c cls: classList){
                classMap.put(cls.Id,cls);
        }
        for(Student__c student: students){
            Class__c classOfStudent = classMap.get(student.Class__c);
            classOfStudent.MyCount__c -= 1; 
        }
        update classMap.values(); 
    }

    public void incrementClassMyCount(List<Student__c> students){
        Set<Id> classIDs = new Set<Id>(); 
        for(Student__c student: students){
            classIDs.add(student.Class__c);
        }
        List<Class__c> classList = new ClassSelector().selectById(classIds); 
        Map<Id,Class__c> classMap = new Map<Id,Class__c>(); 
        for(Class__c cls: classList){
                classMap.put(cls.Id,cls);
        }
        for(Student__c student: students){
            Class__c classOfStudent = classMap.get(student.Class__c);
            classOfStudent.MyCount__c += 1; 
        }
        update classMap.values(); 
    }


}