force-app/main/default/objects/Teach__c.object
<CustomObject>
    <fields>
        <fullName>Subjects__c</fullName>
        <label>Subjects</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hindi</fullName>
                </value>
                <value>
                    <fullName>English</fullName>
                </value>
                <value>
                    <fullName>Maths</fullName>
                </value>
                <value>
                    <fullName>Science</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Teacher__c</fullName>
        <label>Teacher</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Teach</relationshipLabel>
        <relationshipName>Teach</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Teach</label>
    <nameField>
        <label>Teach Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teach</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/selectorClasses/TeachSelector.cls
public with sharing class TeachSelector extends fflib_SObjectSelector {
     public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                Teach__c.id,
                Teach__c.Subjects__c, 
                Teach__c.Teacher__c
        };
    }
     public Schema.SObjectType getSObjectType() {
        return Teach__c.sObjectType;
    }
    public List<Teach__c> selectById(Set<ID> idSet) {
        return (List<Teach__c>) selectSObjectsById(idSet);
    }
    public List<Teach__c> selectAllHindiTeachers(){
        return [SELECT ID FROM Teach__c WHERE Subjects__c = 'Hindi'];
    }
}